[package]
name = "check_nsclient"
version = "0.1.0"
authors = ["Michael Medin <michael@medin.name>"]
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
reqwest = { version = "0.13.1", features = ["json", "query"] }
tokio = { version = "1.49.0", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
serde_yaml = "0.9.33"
tabled = "0.20.0"
anyhow = "1.0.100"
csv = "1.4.0"
indexmap = { version = "2.13.0", features = ["serde"] }
keyring = {  version="3.6.3", features = ["apple-native", "windows-native", "sync-secret-service", "linux-native"] }
async-trait = "0.1.89"
crossterm = "0.29.0"
ratatui = "0.30.0"
tui-prompts = "0.6.1"
confy = "2.0.0"
tokio-util = "0.7.18"

[dev-dependencies]
wiremock = "0.6.5"
mockall = "0.14"
tempfile = "3.24.0"
serial_test = "3.3.1"
