site_name: NSClient++
site_url: https://nsclient.org
repo_url: https://github.com/mickem/nscp
repo_name: GitHub
edit_uri: blob/master/docs/docs
theme: 'material'
theme_dir: 'custom_theme'
copyright: "NSClient++ is released under a GPLv2 license"
extra_css: 
  - pygments.css
  - custom.css
extra:
  #disqus: 'your-disqus-shortname'
  palette:
    primary: 'indigo'
    accent: 'green'
  logo: images/FAVICON.PNG
  root_menu:
    title: 0.5.2
    link: version.md
    page: History
  versions:
    - 0.5.2
    - 0.5.1
    - 0.5.0
    - 0.4.4
    - 0.4.3
    - 0.4.2
pages:
  - Manual:
    - NSClient++: index.md
    - Getting Started: getting_started.md
    - Theory: theory.md
    - Checking Things: checks.md
    - Installing NSClient++: installing.md
    - Configuration: settings.md
    - WEB UI: web.md
    - FAQ: faq.md
  - About:
    - Documentation: about/index.md
    - Whats New: 
      - History: about/whatsnew/index.md
      - 0.4.0: about/whatsnew/0.4.0.md
      - 0.4.1: about/whatsnew/0.4.1.md
      - 0.4.2: about/whatsnew/0.4.2.md
      - 0.4.3: about/whatsnew/0.4.3.md
      - 0.4.4: about/whatsnew/0.4.4.md
      - 0.5.0: about/whatsnew/0.5.0.md
      - 0.5.1: about/whatsnew/0.5.1.md
      - 0.5.2: about/whatsnew/0.5.2.md
    - Building NSClient++: about/build.md
    - Reporting Bugs: about/reporting-bugs.md
    - License: about/license.md
  - Tutorial: tutorial/index.md
  - Howto:
    - Checking things: howto/checks.md
    - Performance Counters: howto/counters.md
    - External scripts: howto/external_scripts.md
    - Running commands: howto/run_commands.md
    - NRPE: howto/nrpe.md
    - NSCA: howto/nsca.md
    - Migrate from 0.3: howto/03x_migration.md
  - Reference:
    - Reference: reference/index.md
    - Check commands:
      - CheckDisk (Windows): reference/windows/CheckDisk.md
      - CheckExternalScripts: reference/check/CheckExternalScripts.md
      - CheckEventLog (Windows): reference/windows/CheckEventLog.md
      - CheckHelpers: reference/check/CheckHelpers.md
      - CheckLogFile: reference/check/CheckLogFile.md
      - CheckMKClient: reference/check/CheckMKClient.md
      - CheckMKServer: reference/check/CheckMKServer.md
      - CheckNet: reference/misc/CheckNet.md
      - CheckNSCP: reference/check/CheckNSCP.md
      - CheckSystemUnix (unix): reference/unix/CheckSystemUnix.md
      - CheckSystem (Windows): reference/windows/CheckSystem.md
      - CheckTaskSched (Windows): reference/windows/CheckTaskSched.md
      - CheckWMI (Windows): reference/windows/CheckWMI.md
    - Clients & Servers:
      - WEBServer: reference/generic/WEBServer.md
      - WEBClient: reference/misc/WEBClient.md
      - NRPEServer: reference/client/NRPEServer.md
      - NRPEClient: reference/client/NRPEClient.md
      - NSClientServer: reference/windows/NSClientServer.md
      - NSCAServer: reference/client/NSCAServer.md
      - NSCAClient: reference/client/NSCAClient.md
      - NRDPClient: reference/client/NRDPClient.md
      - SMTPClient: reference/client/SMTPClient.md
      - GraphiteClient: reference/client/GraphiteClient.md
      - SyslogClient: reference/client/SyslogClient.md
      - CollectdClient: reference/misc/CollectdClient.md
      - Op5Client: reference/misc/Op5Client.md
      - ElasticClient: reference/misc/ElasticClient.md
    - Helper modules:
      - Scheduler: reference/generic/Scheduler.md
      - SimpleFileWriter: reference/generic/SimpleFileWriter.md
      - CommandClient: reference/generic/CommandClient.md
      - SimpleCache: reference/generic/SimpleCache.md
      - PythonScript: reference/generic/PythonScript.md
      - LUAScript: reference/generic/LUAScript.md
      - DotnetPlugins: reference/windows/DotnetPlugins.md
  - Extending:
    - Overview: extending/index.md
    - Python Scripts: extending/python.md
    - Zip Modules: extending/zip-modules.md
  - API:
    - REST:
      - Introduction: api/rest/index.md
      - Info: api/rest/info.md
      - Modules: api/rest/modules.md
      - Queries: api/rest/queries.md
      - Scripts: api/rest/scripts.md
      - Logs: api/rest/logs.md
      - Legacy API: api/rest/legacy.md
    - Plugin API: api/plugin.md

markdown_extensions:
  - admonition
  - codehilite
  - smarty
  - sane_lists
  - toc(permalink=true)
  